apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: content-mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/content-mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: playlists-mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/playlists-mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: statistics-mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/statistics-mongo
