apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlists-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlists
  template:
    metadata:
      labels:
        app: playlists
    spec:
      containers:
        - name: playlists
          image: dariabilkevych/playlists
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: musicapp
            - name: MONGO_URI
              value: 'mongodb://playlists-mongo-srv:27017/playlists'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: playlists-srv
spec:
  selector:
    app: playlists
  ports:
    - name: playlists
      protocol: TCP
      port: 3000
      targetPort: 3000
