apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics
  template:
    metadata:
      labels:
        app: statistics
    spec:
      containers:
        - name: statistics
          image: dariabilkevych/statistics
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: musicapp
            - name: MONGO_URI
              value: 'mongodb://statistics-mongo-srv:27017/statistics'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: statistics-srv
spec:
  selector:
    app: statistics
  ports:
    - name: statistics
      protocol: TCP
      port: 3000
      targetPort: 3000
